version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
        MONGODB_URL: ${MONGODB_URL}
        ENV: ${ENV}
    
    environment:
      - PORT=${PORT}
      - MONGODB_URL=${MONGODB_URL}
      - ENV=${ENV}
    env_file:
      - .env
    ports:
      - "3000:3000"  